version: '3'
services:
  mongodb:
      image: mongo:3.4.14
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
  web:
    build: .
    volumes:
      - .:/app/src
    environment:
      - WSS_URL=${WSS_URL}
    links:
      - mongodb
    depends_on:
      - mongodb
